### ISSUE TITLE
Test methods with parenthesis in their names are correctly retried

### ISSUE THREAD

**Issue by pshevche** [gradle/test-retry-gradle-plugin#269]
```[tasklist]
### Tasks
- [ ] https://github.com/gradle/test-retry-gradle-plugin/issues/123
- [ ] https://github.com/gradle/test-retry-gradle-plugin/issues/101
- [ ] https://github.com/gradle/test-retry-gradle-plugin/issues/263
```
